/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calciter;

import calciter.SamzaSqlQueryParser.QueryInfo;

public class App {
    public String getGreeting() {
        // String sql = "insert into tab1 select t1.* from tab2 t1 inner join tab3 t2 on t1.id=t2.fid ";
        // String sql = "create table tab1 as select t1.* from tab2 t1 inner join tab3 t2 on t1.id=t2.fid ";
        String sql = "create table tab1 as select t1.* from tab2 t1 inner join (select ss.* from ss inner join ss2 on ss.id=ss2.fid) as t2 on t1.id=t2.fid ";
        QueryInfo info = SamzaSqlQueryParser.parseQuery(sql);
        // QueryInfo info = SamzaSqlQueryParser.parseQuery("create table t1 as select * from t2");
        return String.format("sink is: %s, source is: %s", info.getSink(), info.getSources());
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
